#!/bin/bash

build() {
  make
}
run() {
  ./main
}

case "$1" in
build | b)
  build
  exit 0
  ;;
run | r)
  run
  exit 0
  ;;
*)
  echo "Building & running project!"
  build &
  run
  exit 0
  ;;
esac

#Basic bash script "template" to increase building from commandline
#This script can be extended anyway you see fit
